# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/ingil/Document/iatalk/iaclient

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/ingil/Document/iatalk/iaclient

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/ingil/Document/iatalk/iaclient/CMakeFiles /media/ingil/Document/iatalk/iaclient//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/ingil/Document/iatalk/iaclient/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named iaclient

# Build rule for target.
iaclient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 iaclient
.PHONY : iaclient

# fast build rule for target.
iaclient/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/build
.PHONY : iaclient/fast

#=============================================================================
# Target rules for targets named iaclient_autogen

# Build rule for target.
iaclient_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 iaclient_autogen
.PHONY : iaclient_autogen

# fast build rule for target.
iaclient_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient_autogen.dir/build.make CMakeFiles/iaclient_autogen.dir/build
.PHONY : iaclient_autogen/fast

HttpDownload.o: HttpDownload.cpp.o

.PHONY : HttpDownload.o

# target to build an object file
HttpDownload.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/HttpDownload.cpp.o
.PHONY : HttpDownload.cpp.o

HttpDownload.i: HttpDownload.cpp.i

.PHONY : HttpDownload.i

# target to preprocess a source file
HttpDownload.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/HttpDownload.cpp.i
.PHONY : HttpDownload.cpp.i

HttpDownload.s: HttpDownload.cpp.s

.PHONY : HttpDownload.s

# target to generate assembly for a file
HttpDownload.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/HttpDownload.cpp.s
.PHONY : HttpDownload.cpp.s

datapackage.o: datapackage.cpp.o

.PHONY : datapackage.o

# target to build an object file
datapackage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/datapackage.cpp.o
.PHONY : datapackage.cpp.o

datapackage.i: datapackage.cpp.i

.PHONY : datapackage.i

# target to preprocess a source file
datapackage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/datapackage.cpp.i
.PHONY : datapackage.cpp.i

datapackage.s: datapackage.cpp.s

.PHONY : datapackage.s

# target to generate assembly for a file
datapackage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/datapackage.cpp.s
.PHONY : datapackage.cpp.s

iaclient_autogen/mocs_compilation.o: iaclient_autogen/mocs_compilation.cpp.o

.PHONY : iaclient_autogen/mocs_compilation.o

# target to build an object file
iaclient_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/iaclient_autogen/mocs_compilation.cpp.o
.PHONY : iaclient_autogen/mocs_compilation.cpp.o

iaclient_autogen/mocs_compilation.i: iaclient_autogen/mocs_compilation.cpp.i

.PHONY : iaclient_autogen/mocs_compilation.i

# target to preprocess a source file
iaclient_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/iaclient_autogen/mocs_compilation.cpp.i
.PHONY : iaclient_autogen/mocs_compilation.cpp.i

iaclient_autogen/mocs_compilation.s: iaclient_autogen/mocs_compilation.cpp.s

.PHONY : iaclient_autogen/mocs_compilation.s

# target to generate assembly for a file
iaclient_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/iaclient_autogen/mocs_compilation.cpp.s
.PHONY : iaclient_autogen/mocs_compilation.cpp.s

logindialog.o: logindialog.cpp.o

.PHONY : logindialog.o

# target to build an object file
logindialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/logindialog.cpp.o
.PHONY : logindialog.cpp.o

logindialog.i: logindialog.cpp.i

.PHONY : logindialog.i

# target to preprocess a source file
logindialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/logindialog.cpp.i
.PHONY : logindialog.cpp.i

logindialog.s: logindialog.cpp.s

.PHONY : logindialog.s

# target to generate assembly for a file
logindialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/logindialog.cpp.s
.PHONY : logindialog.cpp.s

loginsetdialog.o: loginsetdialog.cpp.o

.PHONY : loginsetdialog.o

# target to build an object file
loginsetdialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/loginsetdialog.cpp.o
.PHONY : loginsetdialog.cpp.o

loginsetdialog.i: loginsetdialog.cpp.i

.PHONY : loginsetdialog.i

# target to preprocess a source file
loginsetdialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/loginsetdialog.cpp.i
.PHONY : loginsetdialog.cpp.i

loginsetdialog.s: loginsetdialog.cpp.s

.PHONY : loginsetdialog.s

# target to generate assembly for a file
loginsetdialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/loginsetdialog.cpp.s
.PHONY : loginsetdialog.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o

.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i

.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s

.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

qrc_rc.o: qrc_rc.cpp.o

.PHONY : qrc_rc.o

# target to build an object file
qrc_rc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/qrc_rc.cpp.o
.PHONY : qrc_rc.cpp.o

qrc_rc.i: qrc_rc.cpp.i

.PHONY : qrc_rc.i

# target to preprocess a source file
qrc_rc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/qrc_rc.cpp.i
.PHONY : qrc_rc.cpp.i

qrc_rc.s: qrc_rc.cpp.s

.PHONY : qrc_rc.s

# target to generate assembly for a file
qrc_rc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iaclient.dir/build.make CMakeFiles/iaclient.dir/qrc_rc.cpp.s
.PHONY : qrc_rc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... iaclient_autogen"
	@echo "... iaclient"
	@echo "... HttpDownload.o"
	@echo "... HttpDownload.i"
	@echo "... HttpDownload.s"
	@echo "... datapackage.o"
	@echo "... datapackage.i"
	@echo "... datapackage.s"
	@echo "... iaclient_autogen/mocs_compilation.o"
	@echo "... iaclient_autogen/mocs_compilation.i"
	@echo "... iaclient_autogen/mocs_compilation.s"
	@echo "... logindialog.o"
	@echo "... logindialog.i"
	@echo "... logindialog.s"
	@echo "... loginsetdialog.o"
	@echo "... loginsetdialog.i"
	@echo "... loginsetdialog.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... qrc_rc.o"
	@echo "... qrc_rc.i"
	@echo "... qrc_rc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

